name: Check file diff
on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    name: Check for deleted files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
      - name: get changed files
        run: |
          git fetch origin main
          echo "FILES=$(git diff --name-status origin/main ${{ github.pull_request.head.sha }})" >> $GITHUB_ENV
      - name: echo output
        run: |
          echo ${{ env.FILES }}
