name: Check file diff
on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    name: Check for deleted files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
      - name: get changed files
        run: |
          # Fetch origin main and get the diff between this branch and the current HEAD sha, then pipe it to wc to count how many files were deleted
          git fetch origin main
          echo "FILES=$(git diff --name-status origin/main ${{ github.pull_request.head.sha }} | wc -l)" >> $GITHUB_ENV
      - name: echo output
        run: |
          echo ${{ env.FILES }}
